# Generated by Django 5.1.7 on 2025-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='inspection_number',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='credential_number',
            field=models.CharField(blank=True, help_text='Full credential number of facility', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration number used for facility login', max_length=100, null=True),
        ),
    ]
