# Generated by Django 5.1.7 on 2025-07-29 08:29

import django.db.models.deletion
import facility_landing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image (recommended: 800x600px or higher)', upload_to=facility_landing.models.gallery_upload_path)),
                ('title', models.CharField(blank=True, help_text='Image title/caption', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the image')),
                ('category', models.CharField(choices=[('rooms', 'Rooms & Living Spaces'), ('common', 'Common Areas'), ('dining', 'Dining Areas'), ('activities', 'Activities & Recreation'), ('exterior', 'Exterior & Grounds'), ('staff', 'Staff & Care'), ('amenities', 'Amenities'), ('other', 'Other')], default='other', help_text='Category for organizing gallery images', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display images (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this image is featured prominently')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='search.facility')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image for the landing page (recommended: 1920x1080px)', null=True, upload_to=facility_landing.models.hero_upload_path)),
                ('hero_tagline', models.CharField(blank=True, help_text='Compelling tagline shown in hero section', max_length=200)),
                ('hero_description', models.TextField(blank=True, help_text='Brief description shown in hero section', max_length=500)),
                ('mission_statement', models.TextField(blank=True, help_text="Facility's mission and philosophy of care")),
                ('facility_story', models.TextField(blank=True, help_text='History and background of the facility')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Number of years in operation', null=True)),
                ('services_description', models.TextField(blank=True, help_text='Detailed description of services and care provided')),
                ('specialized_care', models.TextField(blank=True, help_text='Specialized care programs and treatments')),
                ('accreditations', models.TextField(blank=True, help_text='List of accreditations, certifications, and awards')),
                ('amenities', models.TextField(blank=True, help_text='Facility amenities and features (comma-separated or paragraph format)')),
                ('staff_credentials', models.TextField(blank=True, help_text='Information about staff qualifications and training')),
                ('visiting_hours', models.CharField(blank=True, help_text='Visiting hours information', max_length=200)),
                ('tour_available', models.BooleanField(default=True, help_text='Whether facility tours are available')),
                ('meta_title', models.CharField(blank=True, help_text='Custom page title for SEO (max 60 characters)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Custom meta description for SEO (max 160 characters)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the landing page is publicly visible')),
                ('is_customized', models.BooleanField(default=False, help_text='Whether this landing page has been customized by facility staff')),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='search.facility')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Landing Page',
                'verbose_name_plural': 'Facility Landing Pages',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person giving testimonial', max_length=100)),
                ('author_relation', models.CharField(choices=[('resident', 'Resident'), ('family', 'Family Member'), ('visitor', 'Visitor'), ('professional', 'Healthcare Professional'), ('other', 'Other')], default='family', help_text='Relationship to the facility', max_length=50)),
                ('testimonial_text', models.TextField(help_text='The testimonial content')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Star rating (1-5)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this testimonial prominently')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this testimonial has been approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonials', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='search.facility')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='search.facility')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
