# Generated by Django 5.1.7 on 2025-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylandingpage',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='Whether this landing page has been customized by facility staff'),
        ),
    ]
