# Generated by Django 5.1.7 on 2025-07-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_beds', models.IntegerField(default=0)),
                ('shared_beds_total', models.IntegerField(default=0)),
                ('shared_beds_male', models.IntegerField(default=0)),
                ('shared_beds_female', models.IntegerField(default=0)),
                ('separate_beds_total', models.IntegerField(default=0)),
                ('separate_beds_male', models.IntegerField(default=0)),
                ('separate_beds_female', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bed_availability', to='search.facility')),
            ],
        ),
    ]
