# Generated by Django 5.1.7 on 2025-07-11 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedupdates', '0001_initial'),
        ('search', '0004_alter_facilitychangelog_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedavailability',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='maintenance_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='occupied_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='private_rooms_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='private_rooms_occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='private_rooms_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='shared_beds_female_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='shared_beds_male_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='shared_beds_occupied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bedavailability',
            name='total_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FacilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_private_rooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_shared_rooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('beds_per_shared_room', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('total_rooms', models.IntegerField(default=0)),
                ('total_configured_beds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='search.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('PRIVATE', 'Private Room'), ('SHARED', 'Shared Room')], max_length=10)),
                ('floor', models.CharField(blank=True, max_length=5, null=True)),
                ('wing', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='search.facility')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('facility', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='VACANT', max_length=12)),
                ('gender_assignment', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ANY', 'Any Gender')], default='ANY', max_length=6)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bedupdates.room')),
            ],
            options={
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
