# Generated by Django 5.1.7 on 2025-08-01 09:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedupdates', '0001_initial'),
        ('search', '0004_alter_facilitychangelog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_configured', models.BooleanField(default=False)),
                ('total_rooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('configuration_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_configuration', to='search.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room')], max_length=10)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('room_gender', models.CharField(choices=[('neutral', 'Neutral'), ('male', 'Male'), ('female', 'Female')], default='neutral', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bedupdates.facilityconfiguration')),
            ],
            options={
                'ordering': ['room_name'],
                'unique_together': {('facility_config', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('bed_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied')], default='vacant', max_length=10)),
                ('gender', models.CharField(choices=[('neutral', 'Neutral'), ('male', 'Male'), ('female', 'Female')], default='neutral', max_length=10)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('admitted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bedupdates.room')),
            ],
            options={
                'ordering': ['bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
    ]
