# Generated by Django 5.1.7 on 2025-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='credential_number',
            field=models.CharField(help_text='Can be full format (12345-AGC-2) or just the number (12345)', max_length=100, unique=True),
        ),
    ]
