# Generated by Django 5.1.7 on 2025-07-31 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_facility_credential_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitychangelog',
            options={'verbose_name': 'Facility Pricing', 'verbose_name_plural': 'Facility Pricing'},
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='private_bed_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly rate for private beds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='private_bed_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly rate for private beds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='shared_bed_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly rate for shared beds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='shared_bed_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly rate for shared beds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facilitychangelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_facility_pricing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilitychangelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional pricing notes or conditions'),
        ),
        migrations.CreateModel(
            name='FacilityPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='search.facility')),
            ],
        ),
    ]
